GET http://127.0.0.1:8080/user/role?roleId=1
Accept: application/json


### GET request with parameter
POST http://127.0.0.1:8082/v1/getUserById?id=1
Accept: application/json
Content-Type: application/json
#traceparent: 00-80251b7300d3906b6e9e0b4a1a1f0161-2a26d3c364810663-01
#traceId: 80251b7300d3906b6e9e0b4a1a1f0161

{
  "id": 1
}


### save
POST http://127.0.0.1:8082/v1/save
Accept: application/json
Content-Type: application/json

{
  "user": {
    "nickname": "test",
    "password": "123456",
    "birthday": "2024-01-01",
    "registeredTime": "2024-01-02T12:00:00"
  }
}
