package io.github.loadup.gateway.facade.model;

/*-
 * #%L
 * LoadUp Gateway Facade
 * %%
 * Copyright (C) 2025 - 2026 LoadUp Cloud
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

import java.util.Map;

/**
 * Route configuration model (immutable)
 */
public class RouteConfig {

    /**
     * Route ID (auto-generated, based on path + method)
     */
    private String routeId;

    /**
     * Route name (auto-generated, based on path)
     */
    private String routeName;

    /**
     * Match path
     */
    private String path;

    /**
     * HTTP method
     */
    private String method;

    /**
     * Protocol type (HTTP/RPC/BEAN)
     */
    private String protocol;

    /**
     * Unified target configuration (original string)
     */
    private String target;

    /**
     * Target URL (used for HTTP/RPC)
     */
    private String targetUrl;

    /**
     * Target Bean name (used for BEAN protocol)
     */
    private String targetBean;

    /**
     * Target method name (used for BEAN protocol)
     */
    private String targetMethod;

    /**
     * Whether enabled
     */
    private boolean enabled;

    /**
     * Extended configuration (immutable copy)
     */
    private Map<String, Object> properties;

    /**
     * Parsed timeout (milliseconds)
     */
    private long parsedTimeout;

    /**
     * Parsed retry count
     */
    private int parsedRetryCount;

    /**
     * Parsed wrapResponse (null means use global configuration)
     */
    private Boolean parsedWrapResponse;

    /**
     * Security code for authentication/signing strategy (e.g. "OFF", "default", "hmac")
     */
    private String securityCode;

    public String getRouteId() {
        return routeId;
    }

    public void setRouteId(String routeId) {
        this.routeId = routeId;
    }

    public String getRouteName() {
        return routeName;
    }

    public void setRouteName(String routeName) {
        this.routeName = routeName;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public String getTargetUrl() {
        return targetUrl;
    }

    public void setTargetUrl(String targetUrl) {
        this.targetUrl = targetUrl;
    }

    public String getTargetBean() {
        return targetBean;
    }

    public void setTargetBean(String targetBean) {
        this.targetBean = targetBean;
    }

    public String getTargetMethod() {
        return targetMethod;
    }

    public void setTargetMethod(String targetMethod) {
        this.targetMethod = targetMethod;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public Map<String, Object> getProperties() {
        return properties;
    }

    public void setProperties(Map<String, Object> properties) {
        this.properties = properties;
    }

    public long getParsedTimeout() {
        return parsedTimeout;
    }

    public void setParsedTimeout(long parsedTimeout) {
        this.parsedTimeout = parsedTimeout;
    }

    public int getParsedRetryCount() {
        return parsedRetryCount;
    }

    public void setParsedRetryCount(int parsedRetryCount) {
        this.parsedRetryCount = parsedRetryCount;
    }

    public Boolean getParsedWrapResponse() {
        return parsedWrapResponse;
    }

    public void setParsedWrapResponse(Boolean parsedWrapResponse) {
        this.parsedWrapResponse = parsedWrapResponse;
    }

    public String getSecurityCode() {
        return securityCode;
    }

    public void setSecurityCode(String securityCode) {
        this.securityCode = securityCode;
    }

    // Public read methods return parsed cached values (regular field getters already generated by
    // @Getter)
    public long getTimeout() {
        return this.parsedTimeout;
    }

    public int getRetryCount() {
        return this.parsedRetryCount;
    }

    public Boolean getWrapResponse() {
        return this.parsedWrapResponse;
    }
}
