#!/usr/bin/env python3
"""Merge each Maven module's README and ARCHITECTURE into one Hextra page.

Usage: python3 doc-sync-agent.py [--apply | --check | --build]
Default is a read-only preview. --build applies changes before running Hugo.
The site homepage and documentation landing page are maintained by hand.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
SITE = ROOT / "docs"
CONTENT = SITE / "content" / "docs"
SOURCE_URL = "https://github.com/loadup-cloud/loadup-framework/blob/main/"
DOC_NAMES = ("README.md", "ARCHITECTURE.md")
IGNORED = {".git", ".codegraph", "docs", "target"}
LINK = re.compile(r"(!?\[[^\]]*\]\()([^\s)]+)(\))")
GENERATED_MARKER = "<!-- Generated by doc-sync-agent.py; sources:"


def module_directories() -> list[Path]:
    modules = []
    for pom in ROOT.rglob("pom.xml"):
        relative = pom.relative_to(ROOT)
        if len(relative.parts) < 2 or IGNORED.intersection(relative.parts):
            continue
        module = pom.parent
        missing = [name for name in DOC_NAMES if not (module / name).is_file()]
        if missing:
            raise ValueError(f"{module.relative_to(ROOT)} lacks {', '.join(missing)}")
        modules.append(module)
    return sorted(modules)


def site_path(module: Path) -> Path:
    parts = module.relative_to(ROOT).parts
    family = parts[0]
    if family == "loadup-components":
        slug = module.name.removeprefix("loadup-components-")
        base = CONTENT / "components" / "_index.md" if len(parts) == 1 else CONTENT / "components" / f"{slug}.md"
    elif family == "loadup-commons":
        base = CONTENT / "commons" / "_index.md" if len(parts) == 1 else CONTENT / "commons" / f"{module.name}.md"
    elif family == "loadup-modules":
        slug = module.name.removeprefix("loadup-modules-")
        base = CONTENT / "modules" / "_index.md" if len(parts) == 1 else CONTENT / "modules" / f"{slug}.md"
    elif family == "loadup-testify":
        base = CONTENT / "testing" / "_index.md" if len(parts) == 1 else CONTENT / "testing" / f"{module.name}.md"
    elif family in ("loadup-application", "loadup-dependencies"):
        base = CONTENT / (family.removeprefix("loadup-") + ".md")
    else:
        raise ValueError(f"No site location for {module.relative_to(ROOT)}")
    return base


def source_map(modules: list[Path]) -> dict[Path, Path]:
    mapping = {module / name: site_path(module) for module in modules for name in DOC_NAMES}
    if len(set(mapping.values())) != len(modules):
        raise ValueError("Two Maven modules map to the same Hextra page")
    return mapping


def rewrite_destination(destination: str, source: Path, target: Path, mapping: dict[Path, Path], image: bool) -> str:
    if destination.startswith(("#", "/", "http:", "https:", "mailto:", "data:")):
        return destination
    path_part, marker, fragment = destination.partition("#")
    resolved = (source.parent / path_part).resolve()
    try:
        relative = resolved.relative_to(ROOT)
    except ValueError:
        return destination
    suffix = marker + fragment if marker else ""
    if resolved in mapping:
        # Hugo's default pretty URL treats each Markdown page as a directory.
        # Link to that URL, not to the source .md path that Hugo does not serve.
        page = page_url_directory(mapping[resolved])
        current_page = page_url_directory(target)
        link = Path(os.path.relpath(page, current_page)).as_posix().rstrip("/") + "/"
        if resolved.name == "ARCHITECTURE.md" and not marker:
            return link + "#architecture"
        return link + suffix
    if resolved.is_file():
        base = SOURCE_URL.replace("github.com/", "raw.githubusercontent.com/").replace("/blob/", "/") if image else SOURCE_URL
        return base + quote(relative.as_posix()) + suffix
    return destination


def page_url_directory(page: Path) -> Path:
    return page.parent if page.stem == "_index" else page.with_suffix("")


def rewrite_links(body: str, source: Path, target: Path, mapping: dict[Path, Path]) -> str:
    lines = []
    fence = None
    for line in body.splitlines(keepends=True):
        match = re.match(r"^\s*(```|~~~)", line)
        if match:
            fence = None if fence == match.group(1) else match.group(1)
        if fence is None and not match:
            line = LINK.sub(lambda item: item.group(1) + rewrite_destination(
                item.group(2), source, target, mapping, item.group(1).startswith("!")) + item.group(3), line)
        lines.append(line)
    return "".join(lines)


def source_body(source: Path) -> str:
    body = source.read_text(encoding="utf-8").lstrip("\ufeff")
    if body.startswith("---\n"):
        _, _, body = body.partition("\n---\n")
    return body


def without_title(body: str) -> str:
    return re.sub(r"^# .+\n+", "", body, count=1).strip()


def navigation_title(title: str) -> str:
    title = re.sub(r"\s*::\s*", " ", title)
    title = re.sub(r"\s*[—–]\s*[^—–]*组件\s*$", "", title)
    title = re.sub(r"\s+组件\s*$", "", title)
    return re.sub(r"\s+", " ", title).strip()


def render(module: Path, target: Path, mapping: dict[Path, Path]) -> str:
    readme = module / "README.md"
    architecture = module / "ARCHITECTURE.md"
    readme_body = source_body(readme)
    architecture_body = source_body(architecture)
    match = re.search(r"^# (.+)$", readme_body, re.MULTILINE)
    title = navigation_title(match.group(1)) if match else module.name
    relative = module.relative_to(ROOT).as_posix()
    if module.relative_to(ROOT).parts[0] == "loadup-components":
        # Functional category directories are not Maven modules; keep their component pages visible.
        technical = module != ROOT / "loadup-components" and (module.parent / "pom.xml").is_file()
    else:
        technical = len(module.relative_to(ROOT).parts) > 2 or module.parent.name == "loadup-testify"
    frontmatter = f"---\ntitle: {json.dumps(title, ensure_ascii=False)}\n"
    if technical:
        frontmatter += "sidebar:\n  exclude: true\n"
    frontmatter += "---\n\n"
    marker = f"{GENERATED_MARKER} {relative}/README.md, {relative}/ARCHITECTURE.md -->\n\n"
    intro = rewrite_links(without_title(readme_body), readme, target, mapping).strip()
    design = without_title(architecture_body)
    design = re.sub(r"^(#{2,5}) ", lambda item: "#" + item.group(1) + " ", design, flags=re.MULTILINE)
    design = rewrite_links(design, architecture, target, mapping).strip()
    return frontmatter + marker + f"{intro}\n\n---\n\n<a id=\"architecture\"></a>\n## 设计与实现\n\n{design}\n"


def obsolete_pages(mapping: dict[Path, Path]) -> list[Path]:
    expected = set(mapping.values())
    return sorted(
        path
        for path in CONTENT.rglob("*.md")
        if path not in expected and GENERATED_MARKER in path.read_text(encoding="utf-8")[:512]
    )


def pending(mapping: dict[Path, Path]) -> tuple[list[tuple[Path, str]], list[Path]]:
    updates = []
    for module in sorted({source.parent for source in mapping}):
        target = mapping[module / "README.md"]
        content = render(module, target, mapping)
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            updates.append((target, content))
    return updates, obsolete_pages(mapping)


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Maven module docs to Hugo/Hextra")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--apply", action="store_true", help="write generated pages")
    mode.add_argument("--check", action="store_true", help="fail if generated pages are stale")
    mode.add_argument("--build", action="store_true", help="apply and run hugo --gc --minify")
    args = parser.parse_args()
    if not (SITE / "hugo.toml").is_file():
        parser.error(f"Hugo site not found: {SITE}")
    try:
        modules = module_directories()
        mapping = source_map(modules)
        updates, obsolete = pending(mapping)
    except (OSError, ValueError) as error:
        print(f"Documentation sync failed: {error}", file=sys.stderr)
        return 1
    print(f"{len(modules)} modules; {len(mapping)} source documents; {len(updates)} updates, {len(obsolete)} obsolete pages")
    for path, _ in updates:
        print(f"  update {path.relative_to(ROOT)}")
    for path in obsolete:
        print(f"  remove {path.relative_to(ROOT)}")
    if args.check:
        return int(bool(updates or obsolete))
    if args.apply or args.build:
        for path, content in updates:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        for path in obsolete:
            path.unlink()
    if args.build:
        try:
            result = subprocess.run(["hugo", "--gc", "--minify", "--cleanDestinationDir"], cwd=SITE, check=False)
        except FileNotFoundError:
            print("hugo executable not found", file=sys.stderr)
            return 1
        return result.returncode
    return 0


if __name__ == "__main__":
    sys.exit(main())
