CREATE TABLE merchant_profile (
 id VARCHAR(64) NOT NULL PRIMARY KEY,
 tenant_id VARCHAR(64) NOT NULL,
 merchant_code VARCHAR(64) NOT NULL,
 name VARCHAR(200) NOT NULL,
 short_name VARCHAR(100),
 type VARCHAR(32) NOT NULL,
 industry VARCHAR(64) NOT NULL,
 country VARCHAR(2) NOT NULL,
 province VARCHAR(64),
 city VARCHAR(64),
 address VARCHAR(500),
 registration_no VARCHAR(64),
 contact_name VARCHAR(100),
 contact_phone VARCHAR(32),
 contact_email VARCHAR(200),
 status VARCHAR(16) NOT NULL,
 row_version BIGINT NOT NULL,
 created_by VARCHAR(256) NOT NULL, updated_by VARCHAR(256) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 deleted TINYINT NOT NULL DEFAULT 0,
 UNIQUE KEY uk_merchant_profile_code (tenant_id, merchant_code),
 KEY idx_merchant_profile_page (tenant_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
