package com.github.loadup.components.gateway.plugin.repository.database.dal.daointerface;

import com.github.loadup.components.gateway.plugin.repository.database.dal.dataobject.InstInterfaceMapDO;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>gateway_inst_interface_map</tt>.
 * <p>
 * This file is generated by <tt>gateway-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>gateway</tt> project.
 * <p>
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to directory <tt>dalgen</tt>,
 * and find the corresponding configuration file (<tt>tables/gateway_inst_interface_map.xml</tt>).
 * Modify the configuration file according to your needs, then run <tt>gateway-dalgen</tt> to generate this file.
 */
public interface InstInterfaceMapDAO {

    /**
     * Insert one <tt>InstInterfaceMapDO</tt> object to DB table <tt>gateway_inst_interface_map</tt>, return primary key
     */
    public String insert(InstInterfaceMapDO instInterfaceMap);

    /**
     * Query DB table <tt>gateway_inst_interface_map</tt> for records.
     */
    public List<InstInterfaceMapDO> loadAll();

    /**
     * Query DB table <tt>gateway_inst_interface_map</tt> for records.
     */
    public List<InstInterfaceMapDO> loadByClientId(String clientId);

    /**
     * Query DB table <tt>gateway_inst_interface_map</tt> for records.
     */
    public List<InstInterfaceMapDO> loadByInterfaceId(String interfaceId);

    /**
     * Query DB table <tt>gateway_inst_interface_map</tt> for records.
     */
    public InstInterfaceMapDO loadByClientIdAndInterfaceId(String clientId, String interfaceId);

    /**
     * Delete records from DB table <tt>gateway_inst_interface_map</tt>.
     */
    public int delete(String clientId, String interfaceId);

    /**
     * Delete records from DB table <tt>gateway_inst_interface_map</tt>.
     */
    public int deleteByClientId(String clientId);

    /**
     * Delete records from DB table <tt>gateway_inst_interface_map</tt>.
     */
    public int deleteByInterfaceId(String interfaceId);

}