package com.github.loadup.components.gateway.plugin.repository.database.dal.daointerface;

/*-
 * #%L
 * repository-database-plugin
 * %%
 * Copyright (C) 2022 - 2025 loadup_cloud
 * %%
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * #L%
 */

import com.github.loadup.components.gateway.plugin.repository.database.dal.dataobject.InstDO;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>gateway_inst</tt>.
 * <p>
 * This file is generated by <tt>gateway-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>gateway</tt> project.
 * <p>
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to directory <tt>dalgen</tt>,
 * and find the corresponding configuration file (<tt>tables/gateway_inst.xml</tt>).
 * Modify the configuration file according to your needs, then run <tt>gateway-dalgen</tt> to generate this file.
 */
public interface InstDAO {

	/**
	 * Insert one <tt>InstDO</tt> object to DB table <tt>gateway_inst</tt>, return primary key
	 */
	public String insert(InstDO inst);

	/**
	 * Update DB table <tt>gateway_inst</tt>.
	 */
	public int update(InstDO inst);

	/**
	 * Query DB table <tt>gateway_inst</tt> for records.
	 */
	public List<InstDO> loadAll();

	/**
	 * Query DB table <tt>gateway_inst</tt> for records.
	 */
	public InstDO load(String clientId);

	/**
	 * Query DB table <tt>gateway_inst</tt> for records.
	 */
	public InstDO lock(String clientId);

	/**
	 * Delete records from DB table <tt>gateway_inst</tt>.
	 */
	public int delete(String clientId);

}
