package com.github.loadup.components.gateway.plugin.repository.database.dal.daointerface;

import com.github.loadup.components.gateway.plugin.repository.database.dal.dataobject.InstDO;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>gateway_inst</tt>.
 * <p>
 * This file is generated by <tt>gateway-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>gateway</tt> project.
 * <p>
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to directory <tt>dalgen</tt>,
 * and find the corresponding configuration file (<tt>tables/gateway_inst.xml</tt>).
 * Modify the configuration file according to your needs, then run <tt>gateway-dalgen</tt> to generate this file.
 */
public interface InstDAO {

    /**
     * Insert one <tt>InstDO</tt> object to DB table <tt>gateway_inst</tt>, return primary key
     */
    public String insert(InstDO inst);

    /**
     * Update DB table <tt>gateway_inst</tt>.
     */
    public int update(InstDO inst);

    /**
     * Query DB table <tt>gateway_inst</tt> for records.
     */
    public List<InstDO> loadAll();

    /**
     * Query DB table <tt>gateway_inst</tt> for records.
     */
    public InstDO load(String clientId);

    /**
     * Query DB table <tt>gateway_inst</tt> for records.
     */
    public InstDO lock(String clientId);

    /**
     * Delete records from DB table <tt>gateway_inst</tt>.
     */
    public int delete(String clientId);

}