package com.github.loadup.components.gateway.plugin.repository.database.dal.daointerface;

import com.github.loadup.components.gateway.plugin.repository.database.dal.dataobject.SecurityDO;

import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>gateway_security</tt>.
 * <p>
 * This file is generated by <tt>gateway-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>gateway</tt> project.
 * <p>
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to directory <tt>dalgen</tt>,
 * and find the corresponding configuration file (<tt>tables/gateway_security.xml</tt>).
 * Modify the configuration file according to your needs, then run <tt>gateway-dalgen</tt> to generate this file.
 */
public interface SecurityDAO {

    /**
     * Insert one <tt>SecurityDO</tt> object to DB table <tt>gateway_security</tt>, return primary key
     */
    public String insert(SecurityDO security);

    /**
     * Query DB table <tt>gateway_security</tt> for records.
     */
    public SecurityDO load(String clientId, String securityStrategyCode, String operateType, String algoName);

    /**
     * Query DB table <tt>gateway_security</tt> for records.
     */
    public SecurityDO lock(String clientId, String securityStrategyCode, String operateType, String algoName);

    /**
     * Query DB table <tt>gateway_security</tt> for records.
     */
    public List<SecurityDO> loadAll();

    /**
     * Query DB table <tt>gateway_security</tt> for records.
     */
    public List<SecurityDO> loadByClientId(String clientId);

    /**
     * Update DB table <tt>gateway_security</tt>.
     */
    public int update(SecurityDO security);

    /**
     * Delete records from DB table <tt>gateway_security</tt>.
     */
    public int delete(String clientId, String securityStrategyCode, String operateType, String algoName);

    /**
     * Delete records from DB table <tt>gateway_security</tt>.
     */
    public int deleteByClientId(String clientId);

}