/* Copyright (C) LoadUp Cloud 2022-2025 */
package com.github.loadup.components.gateway.plugin.repository.database.dal.dataobject;

/*-
 * #%L
 * repository-database-plugin
 * %%
 * Copyright (C) 2022 - 2025 loadup_cloud
 * %%
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * #L%
 */

import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 * A data object class directly models database table <tt>gateway_security</tt>.
 * <p>
 * This file is generated by <tt>gateway-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>gateway</tt> project.
 * <p>
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to directory <tt>dalgen</tt>,
 * and find the corresponding configuration file (<tt>tables/gateway_security.xml</tt>).
 * Modify the configuration file according to your needs, then run <tt>gateway-dalgen</tt> to generate this file.
 */
public class SecurityDO {

    // ========== properties ==========

    /**
     * This property corresponds to db column <tt>tenant_id</tt>.
     */
    private String tenantId;

    /**
     * This property corresponds to db column <tt>security_strategy_code</tt>.
     */
    private String securityStrategyCode;

    /**
     * This property corresponds to db column <tt>client_id</tt>.
     */
    private String clientId;

    /**
     * This property corresponds to db column <tt>cert_content</tt>.
     */
    private String certContent;

    /**
     * This property corresponds to db column <tt>operate_type</tt>.
     */
    private String operateType;

    /**
     * This property corresponds to db column <tt>cert_type</tt>.
     */
    private String certType;

    /**
     * This property corresponds to db column <tt>status</tt>.
     */
    private String status;

    /**
     * This property corresponds to db column <tt>key_type</tt>.
     */
    private String keyType;

    /**
     * This property corresponds to db column <tt>algo_name</tt>.
     */
    private String algoName;

    /**
     * This property corresponds to db column <tt>properties</tt>.
     */
    private String properties;

    /**
     * This property corresponds to db column <tt>algo_properties</tt>.
     */
    private String algoProperties;

    /**
     * This property corresponds to db column <tt>gmt_valid</tt>.
     */
    private Date gmtValid;

    /**
     * This property corresponds to db column <tt>gmt_invalid</tt>.
     */
    private Date gmtInvalid;

    /**
     * This property corresponds to db column <tt>gmt_create</tt>.
     */
    private Date gmtCreate;

    /**
     * This property corresponds to db column <tt>gmt_modified</tt>.
     */
    private Date gmtModified;

    // ========== getters and setters ==========

    /**
     *
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     *
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     *
     */
    public String getSecurityStrategyCode() {
        return securityStrategyCode;
    }

    /**
     *
     */
    public void setSecurityStrategyCode(String securityStrategyCode) {
        this.securityStrategyCode = securityStrategyCode;
    }

    /**
     *
     */
    public String getClientId() {
        return clientId;
    }

    /**
     *
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     *
     */
    public String getCertContent() {
        return certContent;
    }

    /**
     *
     */
    public void setCertContent(String certContent) {
        this.certContent = certContent;
    }

    /**
     *
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     *
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType;
    }

    /**
     *
     */
    public String getCertType() {
        return certType;
    }

    /**
     *
     */
    public void setCertType(String certType) {
        this.certType = certType;
    }

    /**
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     *
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     */
    public String getKeyType() {
        return keyType;
    }

    /**
     *
     */
    public void setKeyType(String keyType) {
        this.keyType = keyType;
    }

    /**
     *
     */
    public String getAlgoName() {
        return algoName;
    }

    /**
     *
     */
    public void setAlgoName(String algoName) {
        this.algoName = algoName;
    }

    /**
     *
     */
    public String getProperties() {
        return properties;
    }

    /**
     *
     */
    public void setProperties(String properties) {
        this.properties = properties;
    }

    /**
     *
     */
    public String getAlgoProperties() {
        return algoProperties;
    }

    /**
     *
     */
    public void setAlgoProperties(String algoProperties) {
        this.algoProperties = algoProperties;
    }

    /**
     *
     */
    public Date getGmtValid() {
        return gmtValid;
    }

    /**
     *
     */
    public void setGmtValid(Date gmtValid) {
        this.gmtValid = gmtValid;
    }

    /**
     *
     */
    public Date getGmtInvalid() {
        return gmtInvalid;
    }

    /**
     *
     */
    public void setGmtInvalid(Date gmtInvalid) {
        this.gmtInvalid = gmtInvalid;
    }

    /**
     *
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     *
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     *
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     *
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
