package com.github.loadup.modules.upms.infrastructure.dataobject;

/*-
 * #%L
 * loadup-modules-upms-infrastructure
 * %%
 * Copyright (C) 2022 - 2026 loadup_cloud
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

import com.mybatisflex.core.query.QueryColumn;
import com.mybatisflex.core.table.TableDef;

/**
 * Tables - MyBatis-Flex Generated Table Definitions
 *
 * <p>This class is generated by MyBatis-Flex APT processor and contains static references to all
 * table definitions for type-safe query building.
 *
 * @author MyBatis-Flex APT Processor
 * @since 1.0.0
 */
public class Tables {

  /** Department table definition */
  public static final DepartmentTableDef DEPARTMENT = new DepartmentTableDef();

  /** User table definition */
  public static final UserTableDef USER = new UserTableDef();

  /** Role table definition */
  public static final RoleTableDef ROLE = new RoleTableDef();

  /** Permission table definition */
  public static final PermissionTableDef PERMISSION = new PermissionTableDef();

  /** Login Log table definition */
  public static final LoginLogTableDef LOGIN_LOG = new LoginLogTableDef();

  /** Operation Log table definition */
  public static final OperationLogTableDef OPERATION_LOG = new OperationLogTableDef();

  /** Department Table Definition */
  public static class DepartmentTableDef extends TableDef {
    public final QueryColumn ID = new QueryColumn(this, "id");
    public final QueryColumn PARENT_ID = new QueryColumn(this, "parent_id");
    public final QueryColumn DEPT_NAME = new QueryColumn(this, "dept_name");
    public final QueryColumn DEPT_CODE = new QueryColumn(this, "dept_code");
    public final QueryColumn DEPT_LEVEL = new QueryColumn(this, "dept_level");
    public final QueryColumn SORT_ORDER = new QueryColumn(this, "sort_order");
    public final QueryColumn LEADER_USER_ID = new QueryColumn(this, "leader_user_id");
    public final QueryColumn PHONE = new QueryColumn(this, "phone");
    public final QueryColumn EMAIL = new QueryColumn(this, "email");
    public final QueryColumn STATUS = new QueryColumn(this, "status");
    public final QueryColumn REMARK = new QueryColumn(this, "remark");
    public final QueryColumn TENANT_ID = new QueryColumn(this, "tenant_id");
    public final QueryColumn DELETED = new QueryColumn(this, "deleted");
    public final QueryColumn CREATED_AT = new QueryColumn(this, "created_at");
    public final QueryColumn CREATED_BY = new QueryColumn(this, "created_by");
    public final QueryColumn UPDATED_AT = new QueryColumn(this, "update_at");
    public final QueryColumn UPDATED_BY = new QueryColumn(this, "updated_by");

    public DepartmentTableDef() {
      super("", "upms_department");
    }
  }

  /** User Table Definition */
  public static class UserTableDef extends TableDef {
    public final QueryColumn ID = new QueryColumn(this, "id");
    public final QueryColumn USERNAME = new QueryColumn(this, "username");
    public final QueryColumn PASSWORD = new QueryColumn(this, "password");
    public final QueryColumn NICKNAME = new QueryColumn(this, "nickname");
    public final QueryColumn EMAIL = new QueryColumn(this, "email");
    public final QueryColumn PHONE = new QueryColumn(this, "phone");
    public final QueryColumn AVATAR = new QueryColumn(this, "avatar");
    public final QueryColumn STATUS = new QueryColumn(this, "status");
    public final QueryColumn DEPT_ID = new QueryColumn(this, "dept_id");
    public final QueryColumn REMARK = new QueryColumn(this, "remark");
    public final QueryColumn TENANT_ID = new QueryColumn(this, "tenant_id");
    public final QueryColumn DELETED = new QueryColumn(this, "deleted");
    public final QueryColumn CREATED_AT = new QueryColumn(this, "created_at");
    public final QueryColumn CREATED_BY = new QueryColumn(this, "created_by");
    public final QueryColumn UPDATED_AT = new QueryColumn(this, "update_at");
    public final QueryColumn UPDATED_BY = new QueryColumn(this, "updated_by");

    public UserTableDef() {
      super("", "upms_user");
    }
  }

  /** Role Table Definition */
  public static class RoleTableDef extends TableDef {
    public final QueryColumn ID = new QueryColumn(this, "id");
    public final QueryColumn ROLE_NAME = new QueryColumn(this, "role_name");
    public final QueryColumn ROLE_CODE = new QueryColumn(this, "role_code");
    public final QueryColumn ROLE_LEVEL = new QueryColumn(this, "role_level");
    public final QueryColumn DATA_SCOPE = new QueryColumn(this, "data_scope");
    public final QueryColumn STATUS = new QueryColumn(this, "status");
    public final QueryColumn REMARK = new QueryColumn(this, "remark");
    public final QueryColumn TENANT_ID = new QueryColumn(this, "tenant_id");
    public final QueryColumn DELETED = new QueryColumn(this, "deleted");
    public final QueryColumn CREATED_AT = new QueryColumn(this, "created_at");
    public final QueryColumn CREATED_BY = new QueryColumn(this, "created_by");
    public final QueryColumn UPDATED_AT = new QueryColumn(this, "update_at");
    public final QueryColumn UPDATED_BY = new QueryColumn(this, "updated_by");

    public RoleTableDef() {
      super("", "upms_role");
    }
  }

  /** Permission Table Definition */
  public static class PermissionTableDef extends TableDef {
    public final QueryColumn ID = new QueryColumn(this, "id");
    public final QueryColumn PARENT_ID = new QueryColumn(this, "parent_id");
    public final QueryColumn PERMISSION_NAME = new QueryColumn(this, "permission_name");
    public final QueryColumn PERMISSION_CODE = new QueryColumn(this, "permission_code");
    public final QueryColumn PERMISSION_TYPE = new QueryColumn(this, "permission_type");
    public final QueryColumn SORT_ORDER = new QueryColumn(this, "sort_order");
    public final QueryColumn ICON = new QueryColumn(this, "icon");
    public final QueryColumn ROUTER_PATH = new QueryColumn(this, "router_path");
    public final QueryColumn COMPONENT_PATH = new QueryColumn(this, "component_path");
    public final QueryColumn STATUS = new QueryColumn(this, "status");
    public final QueryColumn REMARK = new QueryColumn(this, "remark");
    public final QueryColumn TENANT_ID = new QueryColumn(this, "tenant_id");
    public final QueryColumn DELETED = new QueryColumn(this, "deleted");
    public final QueryColumn CREATED_AT = new QueryColumn(this, "created_at");
    public final QueryColumn CREATED_BY = new QueryColumn(this, "created_by");
    public final QueryColumn UPDATED_AT = new QueryColumn(this, "update_at");
    public final QueryColumn UPDATED_BY = new QueryColumn(this, "updated_by");

    public PermissionTableDef() {
      super("", "upms_permission");
    }
  }

  /** Login Log Table Definition */
  public static class LoginLogTableDef extends TableDef {
    public final QueryColumn ID = new QueryColumn(this, "id");
    public final QueryColumn USER_ID = new QueryColumn(this, "user_id");
    public final QueryColumn USERNAME = new QueryColumn(this, "username");
    public final QueryColumn LOGIN_TIME = new QueryColumn(this, "login_time");
    public final QueryColumn LOGIN_IP = new QueryColumn(this, "login_ip");
    public final QueryColumn LOGIN_LOCATION = new QueryColumn(this, "login_location");
    public final QueryColumn BROWSER = new QueryColumn(this, "browser");
    public final QueryColumn OS = new QueryColumn(this, "os");
    public final QueryColumn STATUS = new QueryColumn(this, "status");
    public final QueryColumn MESSAGE = new QueryColumn(this, "message");
    public final QueryColumn TENANT_ID = new QueryColumn(this, "tenant_id");
    public final QueryColumn DELETED = new QueryColumn(this, "deleted");
    public final QueryColumn CREATED_AT = new QueryColumn(this, "created_at");
    public final QueryColumn CREATED_BY = new QueryColumn(this, "created_by");
    public final QueryColumn UPDATED_AT = new QueryColumn(this, "update_at");
    public final QueryColumn UPDATED_BY = new QueryColumn(this, "updated_by");

    public LoginLogTableDef() {
      super("", "upms_login_log");
    }
  }

  /** Operation Log Table Definition */
  public static class OperationLogTableDef extends TableDef {
    public final QueryColumn ID = new QueryColumn(this, "id");
    public final QueryColumn USER_ID = new QueryColumn(this, "user_id");
    public final QueryColumn USERNAME = new QueryColumn(this, "username");
    public final QueryColumn OPERATION = new QueryColumn(this, "operation");
    public final QueryColumn METHOD = new QueryColumn(this, "method");
    public final QueryColumn PARAMS = new QueryColumn(this, "params");
    public final QueryColumn TIME = new QueryColumn(this, "time");
    public final QueryColumn IP = new QueryColumn(this, "ip");
    public final QueryColumn TENANT_ID = new QueryColumn(this, "tenant_id");
    public final QueryColumn DELETED = new QueryColumn(this, "deleted");
    public final QueryColumn CREATED_AT = new QueryColumn(this, "created_at");
    public final QueryColumn CREATED_BY = new QueryColumn(this, "created_by");
    public final QueryColumn UPDATED_AT = new QueryColumn(this, "update_at");
    public final QueryColumn UPDATED_BY = new QueryColumn(this, "updated_by");

    public OperationLogTableDef() {
      super("", "upms_operation_log");
    }
  }
}
