<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.loadup-cloud</groupId>
        <artifactId>loadup-parent</artifactId>
        <version>0.0.2-SNAPSHOT</version>
    </parent>

    <artifactId>loadup-components-cache</artifactId>
    <packaging>pom</packaging>
    <name>Loadup Cache Component</name>
    <description>Loadup Cache — API + caffeine/redis binders</description>

    <modules>
        <module>loadup-components-cache-api</module>
        <module>loadup-components-cache-binder-caffeine</module>
        <module>loadup-components-cache-binder-redis</module>
        <module>loadup-components-cache-test</module>
    </modules>
</project>
