<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.loadup-cloud</groupId>
        <artifactId>loadup-parent</artifactId>
        <version>0.0.2-SNAPSHOT</version>
    </parent>

    <artifactId>loadup-components-authserver</artifactId>
    <packaging>pom</packaging>
    <name>LoadUp Components AuthServer</name>
    <description>LoadUp OAuth2 authorization server component (Spring Authorization Server / Keycloak issuer)</description>

    <modules>
        <module>loadup-components-authserver-api</module>
        <module>loadup-components-authserver-binder-sas</module>
        <module>loadup-components-authserver-binder-keycloak</module>
        <module>loadup-components-authserver-test</module>
    </modules>
</project>
