<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.loadup-cloud</groupId>
        <artifactId>loadup-parent</artifactId>
        <version>0.0.2-SNAPSHOT</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>
    <artifactId>loadup-modules-audit-infrastructure</artifactId>
    <name>LoadUp Audit Infrastructure</name>
    <properties>
        <license.useJavaNoReformatCommentStartTag>false</license.useJavaNoReformatCommentStartTag>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.github.loadup-cloud</groupId>
            <artifactId>loadup-modules-audit-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.loadup-cloud</groupId>
            <artifactId>loadup-components-database</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-flyway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
    </dependencies>
</project>
